In [18]:
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd

q_table = np.load('infinite_q_table.npy')

q_table_no_ace = q_table[:][0]
q_table_ace = q_table[:][1]

print(q_table_no_ace.shape)

(2, 2)

In [19]:
q_policy = np.load('infinite_policy.npy')
print(q_policy.shape)
policy_df = pd.DataFrame(q_policy, columns=['No Ace', 'Ace'], index=np.arange(2,21))
policy_df

(19, 2)

    No Ace  Ace
2      1.0  0.0
3      1.0  0.0
4      1.0  0.0
5      1.0  0.0
6      1.0  0.0
7      1.0  0.0
8      1.0  0.0
9      1.0  0.0
10     0.0  0.0
11     1.0  1.0
12     1.0  0.0
13     0.0  0.0
14     0.0  0.0
15     1.0  0.0
16     0.0  0.0
17     1.0  0.0
18     0.0  0.0
19     0.0  0.0
20     0.0  0.0